### PR TITLE
Navbar: version 2

### LINKED ISSUE #938: Navbar: implementation mobile menu
As part of version 2 of the Navbar, a mobile menu following the design in Figma must be implemented. 

Related Issue: https://github.com/Infineon/infineon-design-system-stencil/issues/526

### PR DESCRIPTION
**Pull request by tishoyanchev**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Version 2 of the Navbar component. 
Includes:
- navbar-profile component
- mobile responsiveness
- mobile sidebar

<details>
  <summary>📦 Published PR as canary version: <code>21.0.0--canary.941.641d3065522c0b282a6f5d0606c13e9a0cb290e3.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@21.0.0--canary.941.641d3065522c0b282a6f5d0606c13e9a0cb290e3.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@21.0.0--canary.941.641d3065522c0b282a6f5d0606c13e9a0cb290e3.0
  ```
</details>

### CODE REVIEW

**Review by verena-ifx — CHANGES_REQUESTED** [review]
- the public-storybook folder should not contain a subfolder /fonts. It is correctly ignored in the gitignore folder, so you should make sure not to commit any untracked files, like this folder.

- the current story of the navbar when running storybook is cut off and looks like this: 
image

- the development.mdx file also needs to be updated, as it still contains the documentation for version 1: 
image

- please add the updated navbar to vue, angular and vanilla examples as well

- I'm not sure where and how these states are added?
image

**Review by akashyeole — COMMENTED** [review]
In the ifx-navbar-profile component, the default image is not displayed when imageUrl is not specified.

image
(Screenshot from react example app)

**Comment by verena-ifx** [comment]
There is some spacing to the left of Menu Item 1.
Is this desired?
image

**Comment by tishoyanchev** [comment]
> There is some spacing to the left of Menu Item 1. Is this desired? image

No. Can you describe how to reproduce it?

**Comment by tishoyanchev** [comment]
> @tishoyanchev Can you remove the menu items for the user? or else they are hidden in the mobile menu

I removed the sub menu items in the User menu. The first layer menu items are not hidden in the mobile menu. The profile menu should have items inside. That's the purpose of the menu.

**Pull request merged**
