### PR TITLE
Implemented a maxlength prop for input elements

### LINKED ISSUE #1375: Input components: implement a maxlength Prop
Integrate the native `maxlength` attribute into all components that are based on `input` `text/search`.

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Adds maxlength property to search-field, search-bar, text-field.

Related Issue
#1375 

<details>
  <summary>📦 Published PR as canary version: <code>24.1.1--canary.1388.2fe3e8be060ccb6a0aa174aabbbcbcb9f6f1b788.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@24.1.1--canary.1388.2fe3e8be060ccb6a0aa174aabbbcbcb9f6f1b788.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@24.1.1--canary.1388.2fe3e8be060ccb6a0aa174aabbbcbcb9f6f1b788.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
Can you please resolve the merge conflicts?

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev the conflicts are resolved

**Comment by tishoyanchev** [comment]
> @tishoyanchev the conflicts are resolved

Can you do it again?

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev done

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
changes are not reflected in the example apps - react, vue

**Pull request merged**
