### PR TITLE
Form integration for radio-button, checkbox, text-field, switch and date-picker

### LINKED ISSUE #1158: Form integration for radio-button, checkbox and text-field
The radio-button, text-field and checkbox components do not have a Form integration. When used inside a Form, their values do not get submitted. 
Form integration would require a new attribute `name` to both components.

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Added form integration to radio-button, checkbox, text-field, switch and date-picker components.
Uses stencil [formAssociated](https://stenciljs.com/docs/form-associated) to implement the integration

Related Issue
#1158 

<details>
  <summary>📦 Published PR as canary version: <code>23.0.1--canary.1284.b868ff709931a5f5c75807639ac089ae54d5e8aa.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@23.0.1--canary.1284.b868ff709931a5f5c75807639ac089ae54d5e8aa.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@23.0.1--canary.1284.b868ff709931a5f5c75807639ac089ae54d5e8aa.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
The values are still not submitted. 
I don't understand the changes that you have made, and their intended goal. 
You have removed the `name` property, and included the `attachedInternals `decorator. It is unclear to me what is this decorator do, and what is it supposed to achieve? Could you please explain your changes.

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev I follwed the [stencil documentation for form-associated components](https://stenciljs.com/docs/form-associated).
The name property doesn't need to be explicitly mentioned, however I can add it again if prefered.

I tested whether it works with the E2E tests and with this form in the index.html:
```html
    <form id="testForm" action="http://www.example.com" method="get" >
      <ifx-text-field id="formName" name="name"></ifx-text-field>
      <ifx-radio-button id="formRadio" name=radio></ifx-radio-button>
      <ifx-checkbox id="formCheckbox" name="checkbox"></ifx-checkbox>
      <ifx-button type="submit" theme="default" size="s" disabled="false" icon="false">
        Submit form
      </ifx-button>
      <ifx-button type="reset" variant="secondary" theme="default" size="s" disabled="false" icon="false">
        Reset form
      </ifx-button>
    </form>
```

**Comment by tishoyanchev** [comment]
> @tishoyanchev I follwed the [stencil documentation for form-associated components](https://stenciljs.com/docs/form-associated). The name property doesn't need to be explicitly mentioned, however I can add it again if prefered.
> 
> I tested whether it works with the E2E tests and with this form in the index.html:
> 
> ```
>     <form id="testForm" action="http://www.example.com" method="get" >
>       <ifx-text-field id="formName" name="name"></ifx-text-field>
>       <ifx-radio-button id="formRadio" name=radio></ifx-radio-button>
>       <ifx-checkbox id="formCheckbox" name="checkbox"></ifx-checkbox>
>       <ifx-button type="submit" theme="default" size="s" disabled="false" icon="false">
>         Submit form
>       </ifx-button>
>       <ifx-button type="reset" variant="secondary" theme="default" size="s" disabled="false" icon="false">
>         Reset form
>       </ifx-button>
>     </form>
> ```

So does it work for you? When you submit the form, the values are submitted too? They're not being submitted for me.

**Comment by tishoyanchev** [comment]
> @tishoyanchev I follwed the [stencil documentation for form-associated components](https://stenciljs.com/docs/form-associated). The name property doesn't need to be explicitly mentioned, however I can add it again if prefered.
> 
> I tested whether it works with the E2E tests and with this form in the index.html:
> 
> ```
>     <form id="testForm" action="http://www.example.com" method="get" >
>       <ifx-text-field id="formName" name="name"></ifx-text-field>
>       <ifx-radio-button id="formRadio" name=radio></ifx-radio-button>
>       <ifx-checkbox id="formCheckbox" name="checkbox"></ifx-checkbox>
>       <ifx-button type="submit" theme="default" size="s" disabled="false" icon="false">
>         Submit form
>       </ifx-button>
>       <ifx-button type="reset" variant="secondary" theme="default" size="s" disabled="false" icon="false">
>         Reset form
>       </ifx-button>
>     </form>
> ```

For some reason it worked this time. I will review it again and then merge it. Good job.

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
- when the `disabled` property is added (`disabled="false"`), the value is not submitted. This goes for radio-button, checkbox and text-field.
- can you also add the `name` attribute on these components in storybook? 
- can you also add form integration to `ifx-switch` and `ifx-date-picker`?

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev The element is disabled once the disabled property is present, exactly as in default HTML components, e.g. `<input disabled></input>`.
Stencil also has an [Issue about this topic](https://github.com/ionic-team/stencil/issues/5461) and if I understood correctly, the behaviour we currently have would comply with the standard.

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
- About the disabled. Interesting discussion! I can't say I agree with it, but at least now we know. 
- About the name attribute. I can see it in stories file, but it's not reflected in the actual storybook page. It's not there. 
- Could you please resolve the merge conflict? This could also be the reason for the name attribute not showing up in SB

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev 
I resolved the merge conflict and added the description for the text field. 
However, I somehow already saw the name property in the storybook without this change.
Maybe we should consider adding something like a devcontainer, if we keep having these issues, or is that only with me?

**Comment by tishoyanchev** [comment]
> @tishoyanchev I resolved the merge conflict and added the description for the text field. However, I somehow already saw the name property in the storybook without this change. Maybe we should consider adding something like a devcontainer, if we keep having these issues, or is that only with me?

Looks good now. I can see the prop name in Storybook now. 
Can you please also resolve the failed check?

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev should be ready now. Seems like the pipeline just had network issues

**Pull request merged**
