### PR TITLE
Sidebar: links are now removable

### LINKED ISSUE #992: Sidebar: links should be removable
Links - **Terms of use** ,**Imprint** and **Privacy policy** should be removable.

### PR DESCRIPTION
**Pull request by akashyeole**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Description
Sidebar links are now removable using boolean props -> displayPrivacyPolicyLink, displayTermsOfUseLink and displayImprintLink

Related Issue
#992 

<details>
  <summary>📦 Published PR as canary version: <code>20.49.0--canary.994.5112548ff02e52c742b3b948da13fdff642e0108.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.49.0--canary.994.5112548ff02e52c742b3b948da13fdff642e0108.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.49.0--canary.994.5112548ff02e52c742b3b948da13fdff642e0108.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@akashyeole 
Could you replace the displayPrivacyPolicyLink props logic with just empty url being used as a condition for displaying them? This is what we discussed in Verena's PR about the Footer links. Please go through the comments there. 
Instead of creating a separate Prop, **displayPrivacyPolicyLink**, for conditionally removing/showing the links, you could just use the existing **privacyPolicy** Prop. When it's empty string, it means no url is passed, which means the user does not want it, so you could use it for conditionally removing the link.

**Comment by tishoyanchev** [comment]
@akashyeole 
Please add a Prop for the removal and editing of the **copyrights** text. Follow the current model of the Footer from master branch.
Also keep in mind that Copyrights text is not a link. It's a static text that needs to be customizable as well.

**Comment by akashyeole** [comment]
@tishoyanchev 
Implemented copyright-text prop to edit/remove copyright text.

**Comment by tishoyanchev** [comment]
- Why is the default value of the copyright text "R"?
- link props, including the copyright text should have default values. 

Please follow the example of the current Footer component!

**Comment by tishoyanchev** [comment]
Can you please resolve the merge conflicts?

**Comment by tishoyanchev** [comment]
1. When **copyright-text** is removed, the space it occupied remains. This is due to the **flex-gap**, and the fact that, the **copyrights-text** element is still in the DOM. A solution is to use a **State** to update a class which sets the element to `display: none`. This will remove it from the DOM. 
2. While not directly part of this PR, an indirect issue is that when only imprint and privacy-policy are used, they don't occupy the same row. A simple solution could be to just use **flex-wrap**.

**Comment by akashyeole** [comment]
@tishoyanchev 
> 1. When **copyright-text** is removed, the space it occupied remains. This is due to the **flex-gap**, and the fact that, the **copyrights-text** element is still in the DOM. A solution is to use a **State** to update a class which sets the element to `display: none`. This will remove it from the DOM.
> 2. While not directly part of this PR, an indirect issue is that when only imprint and privacy-policy are used, they don't occupy the same row. A simple solution could be to just use **flex-wrap**.

Fixed 1). I will create a new issue for 2).

**Pull request merged**
