### PR TITLE
Sidebar: v-2

### PR DESCRIPTION
**Pull request by tishoyanchev**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Outdated PR. 
Refer to https://github.com/Infineon/infineon-design-system-stencil/pull/791

<details>
  <summary>📦 Published PR as canary version: <code>20.35.0--canary.702.a7e66dd103650675b1d2237581023037405f3375.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.35.0--canary.702.a7e66dd103650675b1d2237581023037405f3375.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.35.0--canary.702.a7e66dd103650675b1d2237581023037405f3375.0
  ```
</details>

### CODE REVIEW

**Review by verena-ifx — CHANGES_REQUESTED** [review]
can you update storybook to inform the user of the new possibilities as well?

**Comment by verena-ifx** [comment]
> ition of nested items is not

just add a story, as we discussed. A story that demonstrates the nesting possibilities

**Comment by verena-ifx** [comment]
One more thing, the sub menu doesnt open when clicking on the arrow: 
image

**Comment by tishoyanchev** [comment]
> > ition of nested items is not
> 
> just add a story, as we discussed. A story that demonstrates the nesting possibilities

Already added.

**Comment by verena-ifx** [comment]
And: The sidebar currently does not support keyboard events. Each item + the submenu should be accessible via keyboard as well

**Pull request closed without merging**
