### PR TITLE
Tabs: restored active-tab-index functionality

### LINKED ISSUE #1359: Tabs: restore the active-tab-index functionality
The Tabs component used to have an active-tab-index feature.
Currently, only the Prop name remains, but the logic and functionality is gone. 
Bring back or re-create the active-tab-index functionality again.

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Restore the active tab functionality and add corresponding tests.

Related Issue
#1245 #1359

<details>
  <summary>📦 Published PR as canary version: <code>24.1.2--canary.1389.03c768a716edcad4fc4a429d06ba9f63c85d92d7.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@24.1.2--canary.1389.03c768a716edcad4fc4a429d06ba9f63c85d92d7.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@24.1.2--canary.1389.03c768a716edcad4fc4a429d06ba9f63c85d92d7.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
- you have to do a clean install, otherwise, the app is not working
- const tabs = await page.find('ifx-tabs') unused line
- when `active-tab-index` is set to tab that does not exist, active tab should be the last one. Currently, the component does not render

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev I have the changes ready. Should I push it, or do you want to try to fix this first?

**Comment by tishoyanchev** [comment]
> @tishoyanchev I have the changes ready. Should I push it, or do you want to try to fix this first?

Please push your changes, and tell me how you resolved it? I keep getting this angular error.

**Comment by pfafffabian-ifx** [comment]
> > @tishoyanchev I have the changes ready. Should I push it, or do you want to try to fix this first?
> 
> Please push your changes, and tell me how you resolved it? I keep getting this angular error.

unfortunately only the unused line and the behaviour if the tab doesnt exist.  
The angular error confuses me too

**Comment by tishoyanchev** [comment]
> > > @tishoyanchev I have the changes ready. Should I push it, or do you want to try to fix this first?
> > 
> > 
> > Please push your changes, and tell me how you resolved it? I keep getting this angular error.
> 
> unfortunately only the unused line and the behaviour if the tab doesnt exist. The angular error confuses me too

What do you mean? Could you not resolve the issue?

**Comment by pfafffabian-ifx** [comment]
> > > > @tishoyanchev I have the changes ready. Should I push it, or do you want to try to fix this first?
> > > 
> > > 
> > > Please push your changes, and tell me how you resolved it? I keep getting this angular error.
> > 
> > 
> > unfortunately only the unused line and the behaviour if the tab doesnt exist. The angular error confuses me too
> 
> What do you mean? Could you not resolve the issue?

I don't know how to resolve the angular error either. I just fixed your other remarks

**Pull request merged**
