### PR TITLE
Stepper: implemented `disabled` prop for ifx-step

### LINKED ISSUE #1395: Stepper: implement a disable Prop for each Step
The Step component must have a a disable prop that would allow the user to disable the step even when in a completed state. When a completed Step has been disabled, it remains in a completed state, but it cannot be clicked again. It is therefore unclickable. 

In addition: implement the design related ticket: https://github.com/Infineon/infineon-design-system-stencil/issues/1437

### LINKED ISSUE #1437: Stepper: align design to latest changes
Align the states of the Stepper with the latest design: https://www.figma.com/design/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?node-id=17858-11227&m=dev

Also, on compact variant, the text should be aligned to the left side. `text-align: left`;

### PR DESCRIPTION
**Pull request by akashyeole**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Description
Implemented the `disabled` prop for ifx-step component, when set, step cannot be clicked. 
Updated the ifx-link variant to menu.

Related Issue
#1395 
#1437 

<details>
  <summary>📦 Published PR as canary version: <code>25.3.0--canary.1408.572ada51431ef07e9e703b10003db6e7f9f04970.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@25.3.0--canary.1408.572ada51431ef07e9e703b10003db6e7f9f04970.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@25.3.0--canary.1408.572ada51431ef07e9e703b10003db6e7f9f04970.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@akashyeole 
The `disabled` state is incorrect.

**Comment by verena-ifx** [comment]
Is there any update on this @akashyeole ?

**Comment by tishoyanchev** [comment]
@akashyeole 
Did you make the changes from this Issue? https://github.com/Infineon/infineon-design-system-stencil/issues/1437

**Comment by tishoyanchev** [comment]
Ready for merge. 
Waiting for react issue to be fixed so all checks can pass.

**Review by tishoyanchev — APPROVED** [review]

**Pull request merged**
