### PR TITLE
Enhancement: Add configurable step size to slider component

### LINKED ISSUE #1122: Slider: configurable step size
Current step size value is fixed to 1.
Allow the user to customize the step size to any value they want (eg. 0.1/5 etc.)

### PR DESCRIPTION
**Pull request by verena-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Step size in slider component can now be configured by user

<details>
  <summary>📦 Published PR as canary version: <code>21.10.0--canary.1186.b2e1ac727113a274b4f894191d4d8951d6e4882a.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@21.10.0--canary.1186.b2e1ac727113a274b4f894191d4d8951d6e4882a.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@21.10.0--canary.1186.b2e1ac727113a274b4f894191d4d8951d6e4882a.0
  ```
</details>

### CODE REVIEW

**Comment by verena-ifx** [comment]
Let's resolve the merge conflicts and do the review together @pfafffabian-ifx

**Comment by tishoyanchev** [comment]
Note: make sure the configurable step-size can also be applied to both handles when used.

**Comment by verena-ifx** [comment]
@pfafffabian-ifx @tishoyanchev if this is fixed, we can merge it

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev 
I think it should be fixed now.
However, I couldn't see the warning when running the storybook and the examples.
What did you run to see it?

**Comment by tishoyanchev** [comment]
> @tishoyanchev I think it should be fixed now. However, I couldn't see the warning when running the storybook and the examples. What did you run to see it?

I ran the app using index.html, but it also appears on our example apps (react, vue, angular).

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev strange, i ran all examples on the erroneous commit again, but still didn't get the warning. 
Do you have any idea why? And could you confirm that my last commit removed the warning?

I only have this in the console, but those are related to different components:
image

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
I don't see the warning anymore.

**Pull request merged**
