### PR TITLE
chore: bump copyright date to current year

### PR DESCRIPTION
**Pull request by curtdept**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Description
This PR bumps the copyright line to the current year. This is observed in our DDS based footers on the OSTS Platform.

### CODE REVIEW

**Comment by curtdept** [comment]
@verena-ifx do you mind reviewing this one please :)

**Comment by akashyeole** [comment]
Instead of using hard value of year, we can use `{ new Date().getFullYear() }`.

**Comment by verena-ifx** [comment]
> new Date().getFullYear()

Thanks a lot for contributing Curtis, really appreciate it! I am currently working on some improvements for the footer components myself, so I would just include your change in that Pull Request, if you are fine with that :)

**Comment by curtdept** [comment]
> > new Date().getFullYear()
> 
> Thanks a lot for contributing @curtdept @akashyeole , really appreciate it! I am currently working on some improvements for the footer components myself, so I would just include your change in that Pull Request, if you are fine with that :)

Sounds good, I'll close this one

**Comment by curtdept** [comment]
Closing as per above

**Pull request closed without merging**
