### PR TITLE
187 review radio button

### PR DESCRIPTION
**Pull request by verena-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Radio Button review

<details>
  <summary>📦 Published PR as canary version: <code>18.2.12--canary.210.ed48f2ca4e986427b920e468e2fb332e33b0544a.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@18.2.12--canary.210.ed48f2ca4e986427b920e468e2fb332e33b0544a.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@18.2.12--canary.210.ed48f2ca4e986427b920e468e2fb332e33b0544a.0
  ```
</details>

### CODE REVIEW

**Comment by SergejLust** [comment]
@verena-ifx:
- default state is wrong (focus border is visible)
- focus border should only be visible if I use TAB and it should be ocean
- wrong radio-button height (must be 20px at all sizes)
- wrong font-family
- m font-size and line-height are wrong

Please check here the current design. Also change to dev mode to click on the "Open in playground" Button and play with the properties:
https://www.figma.com/file/zPvPwPgb4EsYFXKC2nhzSG/Infineon-DDS-%7C-Main?type=design&node-id=2583-7344&mode=design&t=WU5725lpM5VfJazW-4

**Comment by tishoyanchev** [comment]
- when error is true, I can't switch the button on/off
- when size is "" empty quotes, border is gone
- { eventName: 'ifxChange' } why is this necessary?
- there is unused code in stylesheet 
        justify-content: center;
        align-items: center;
        under .radioButton__wrapper
- what does    
  &.disabled::after { 
     background-color: #BFBBBB;
   } 
do?

- what is the purpose of onIfxChange in the storybook?
-  tags: ['autodocs'], is commented out.

**Comment by verena-ifx** [comment]
> * , I can't switch the button on/off

Thanks Tisho, will take care of it today. As for the event, we need to emit an event when the button status changes.

**Comment by tishoyanchev** [comment]
> As for the event, we need to emit an event when the button status changes. and the event in storybook makes sure that you see an action when the button is clicked to demonstrate event emission

Then maybe we should just hide it from the controls, since it's not an actual control option? 

```
Default.argTypes = {
  onIfxChange : {
    table: {
      disable: true
    }
  }
}
```

**Comment by verena-ifx** [comment]
> * justify-content: center;
>   align-items: center;
>   under .radioButton__wrapper

oh and tags autodocs is commented out to highlight that a custom mdx story is used for this component. I would suggest to leave it this way for the components that have a custom docs page

**Pull request merged**
