### PR TITLE
Align Radio-Button, Checkbox and Switch to web standards

### LINKED ISSUE #1476: Input components: name attribute is missing
Investigate if the input-based components need a name prop, and implement one if necessary. 
In addition: remove the disabled prop from the Storybook snippet as the present of a disabled prop, even if set to false, will disable the submission. This can cause a confusion and misunderstanding.

### LINKED ISSUE #1479: Radio-button, Checkbox and Switch: align to web standards
radio-button, checkbox and switch components have a value property instead of checked prop. Replace value with checked for on/off behavior, and introduce 'value' as a string. 
In addition:
Two radio-buttons with the same name attribute do not toggle because the radio-button component is made up of <div> elements. The input element is missing. 
Integrate the Input element following the example of the checkbox component, and make sure two radio-buttons with the same name toggle. 

Related issue: https://github.com/Infineon/infineon-design-system-stencil/issues/1476

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
- Rename the value property of Checkbox, Switch, Radio-Button to checked
- Implement Radio Button group behaviour

Related Issue
Closes #1479 
Fixes #1476 for the Radio Button

<details>
  <summary>📦 Published PR as canary version: <code>26.0.0--canary.1485.8162da32f9fc366646a6da72bbed42526db2b8ee.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@26.0.0--canary.1485.8162da32f9fc366646a6da72bbed42526db2b8ee.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@26.0.0--canary.1485.8162da32f9fc366646a6da72bbed42526db2b8ee.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
- when `radio-button` is disabled, `event` is still emitted on click.
- Radio-button warning message: `"inputElement" State changed during rendering. This can potentially lead to infinite-loops and other bugs.` In short, the `inputElement` `State` should not be mutated during rendering time. 
- remove `disabled` attribute from the storybook snippet of `Switch` and `Checkbox`.
- `value` prop is missing from `Radio-button`, `Checkbox` and `Switch`. The value of the `value` prop is submitted in a `form`.

**Comment by verena-ifx** [comment]
The checkbox doesnt have the "disabled" arg in the story anymore. Not sure why this got removed, but the checkbox should be "disable-able"

**Comment by verena-ifx** [comment]
> @pfafffabian-ifx
> 
> * when `radio-button` is disabled, `event` is still emitted on click.
> * Radio-button warning message: `"inputElement" State changed during rendering. This can potentially lead to infinite-loops and other bugs.` In short, the `inputElement` `State` should not be mutated during rendering time.
> * remove `disabled` attribute from the storybook snippet of `Switch` and `Checkbox`.
> * `value` prop is missing from `Radio-button`, `Checkbox` and `Switch`. The value of the `value` prop is submitted in a `form`.
> * Remove `name="search_terms"` from `single-select`. `Name` prop can be set by the users.
> * Selected options are not submitted for the `multi-select`. Should they?

@pfafffabian-ifx you renamed value to checked, as I could see. Fine with me, if this is in accordance with the web standard. But yes, @tishoyanchev is right, value is still used in the code as well. What do you mean by the select options not being submitted?

**Comment by tishoyanchev** [comment]
> The checkbox doesnt have the "disabled" arg in the story anymore. Not sure why this got removed, but the checkbox should be "disable-able"

@verena-ifx 

I told Fabian to remove it from the snippet to avoid confusion because when the disabled attribute is present, even if set to true, the value attribute doesn't work, and no value is submitted. This might confuse users, so I told him to just remove it from the snippet.

**Comment by tishoyanchev** [comment]
> What do you mean by the select options not being submitted?

@verena-ifx 

When you put  the multi-select component inside a <form>, and select multiple options, and then submit it, the options were not getting submitted, but his is already resolved.

**Pull request merged**
