### PR TITLE
188 review search input

### PR DESCRIPTION
**Pull request by tishoyanchev**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Reviewed the Search Input, and updated the following:
- removed unused Props 
- added states (hover/focused)
- removed slot for nesting the ifx-icon
- optimized the code
- removed borderColor as Props
- on hover over delete icon, mouse is now cursor
- fixed the size Prop
- re[;aced #fff with its corresponding token
- added focus state
- updated storybook 
- added the component in the example apps
- imbedded ifx-icon inside the component

<details>
  <summary>📦 Published PR as canary version: <code>19.1.0--canary.219.a73c85509cb1258e7f230b123d24bbcf2ff702d3.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@19.1.0--canary.219.a73c85509cb1258e7f230b123d24bbcf2ff702d3.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@19.1.0--canary.219.a73c85509cb1258e7f230b123d24bbcf2ff702d3.0
  ```
</details>

### CODE REVIEW

**Comment by verena-ifx** [comment]
I re-added v-model support within the Vue Wrapper example applications
renamed component to search-field instead of search-input
simplified the event emission (again :D)

**Comment by verena-ifx** [comment]
one thing i noted: in the vanilla example app, for the search-bar, the background is not transparent. if the background of the parent has another color, you can just see a white bar of 100% width. not sure if thats how it should be 
image

**Comment by verena-ifx** [comment]
what do we do about the delete icon btw? its different in our icon library to the one on figma

**Comment by tishoyanchev** [comment]
**new changes** commit contains the following changes:
- Commented out _@Prop() inSidebar: boolean = false;_ What is it used for?
- Commented out _@Prop() hideLabel: boolean = false;_ What is it used for?
- Adjusted the height. The search-bar had a height of 40px, but the nested search-input was 48px. Sergej and I spoke, and agreed to get rid of the 48px variant. So I adjusted the height to only 40px.
- Commented out updateViewportClass function because: 
a) It is not needed anymore
b) responsive design should be set in the stylesheet with media queries
c) there was a bug; 'small' class removes the 'search' label next to the search icon, and never re-adds it. This is what (I believe) Sergej meant by his "triggers not working" comment.

I also closed 189 PR.

**Comment by verena-ifx** [comment]
> **new changes** commit contains the following changes:
> 
> * Commented out _@prop() inSidebar: boolean = false;_ What is it used for?
> * Commented out _@prop() hideLabel: boolean = false;_ What is it used for?
> * Adjusted the height. The search-bar had a height of 40px, but the nested search-input was 48px. Sergej and I spoke, and agreed to get rid of the 48px variant. So I adjusted the height to only 40px.
> * Commented out updateViewportClass function because:
>   a) It is not needed anymore
>   b) responsive design should be set in the stylesheet with media queries
>   c) there was a bug; 'small' class removes the 'search' label next to the search icon, and never re-adds it. This is what (I believe) Sergej meant by his "triggers not working" comment.
> 
> I also closed 189 PR.

The Search Label should be removed when the viewport has a certain width... That's what Sergej told me. Hence the updateViewportClass method.

**Comment by verena-ifx** [comment]
@SergejLust The triggers controlling the opening of the search-bar when it is closed will not be visible in storybook. They only apply when the search-bar is used within the navbar component. I got confused by the comment about the triggers and added them for all viewports, but as we discussed earlier, they should only be applied when used within the navbar. Will add the search-bar component within the navbar to the example applications, so it is visible/testable from there.

**Review by verena-ifx — APPROVED** [review]
Looks good from my end!

**Pull request merged**
