### PR TITLE
Examples added for vue, react, angular and vanilla js

### PR DESCRIPTION
**Pull request by verena-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

This branch includes an examples folder with a vue and vanilla application for testing our web components.

<details>
  <summary>📦 Published PR as canary version: <code>18.0.1--canary.48.ed67aff39aac3bea1209309f3427bf557752e5b2.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@18.0.1--canary.48.ed67aff39aac3bea1209309f3427bf557752e5b2.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@18.0.1--canary.48.ed67aff39aac3bea1209309f3427bf557752e5b2.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
The CDN used in the vanilla-CDN is wrong. 
This is the latest one: https://webnetprod.muc.infineon.com/npm/ifx/infineon-design-system-stencil.esm.js

**Comment by verena-ifx** [comment]
> The CDN used in the vanilla-CDN is wrong. This is the latest one: https://webnetprod.muc.infineon.com/npm/ifx/infineon-design-system-stencil.esm.js

Actually, unpkg is an opensource alternative and does work, too. But if you created another link, I can include this one

**Comment by tishoyanchev** [comment]
> > The CDN used in the vanilla-CDN is wrong. This is the latest one: https://webnetprod.muc.infineon.com/npm/ifx/infineon-design-system-stencil.esm.js
> 
> Actually, unpkg is an opensource alternative and does work, too. But if you created another link, I can include this one

The unpkg is just a hosting service. Not a real CDN. The link I gave you is hosted on internal Infineon premises and is designed to improve performance on the intranet. It is the intranet equivalent to a CDN. You can discard any internet alternatives like unpkg.

**Comment by verena-ifx** [comment]
> > > The CDN used in the vanilla-CDN is wrong. This is the latest one: https://webnetprod.muc.infineon.com/npm/ifx/infineon-design-system-stencil.esm.js
> > 
> > 
> > Actually, unpkg is an opensource alternative and does work, too. But if you created another link, I can include this one
> 
> The unpkg is just a hosting service. Not a real CDN. The link I gave you is hosted on internal Infineon premises and is designed to improve performance on the intranet. It is the intranet equivalent to a CDN. You can discard any internet alternatives like unpkg.

Unpkg is a cdn actually, but you are right, if we got an Infineon-internal alternative, we should use this one: I updated the PR

**Comment by tishoyanchev** [comment]
Why does the folder only include vue and vanilla for testing? What about React and Angular?

**Comment by verena-ifx** [comment]
> Why does the folder only include vue and vanilla for testing? What about React and Angular?

Those should be added of course. But this version only has vue + vanilla so it can be built up upon them

**Comment by tishoyanchev** [comment]
> > Why does the folder only include vue and vanilla for testing? What about React and Angular?
> 
> Those should be added of course. But this version only has vue + vanilla so it can be built up upon them

Why do we need only this version? Why not do the complete task, and then make the PR? Is it urgent that we have a test folder for vue and vanilla?

**Comment by kaiwerther** [comment]
can you add a github pages deployment for these two projects and resolve the merge conflicts?

**Review by kaiwerther — CHANGES_REQUESTED** [review]
add automatic deployment for these projects to github pages

**Comment by verena-ifx** [comment]
> add automatic deployment for these projects to github pages

Very good point (y) Will add it

**Comment by verena-ifx** [comment]
@kaiwerther Should I merge this one?

**Pull request merged**
