### PR TITLE
New component: Table (advanced version)

### PR DESCRIPTION
**Pull request by verena-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Text alignment fixed
Table demonstration in example apps fixed

<details>
  <summary>📦 Published PR as canary version: <code>25.7.4--canary.988.8b8351c1e98caecb12fb6c89d398c9b88208742a.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@25.7.4--canary.988.8b8351c1e98caecb12fb6c89d398c9b88208742a.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@25.7.4--canary.988.8b8351c1e98caecb12fb6c89d398c9b88208742a.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
- What is the purpose of the time showing when no **rows** or **cols**?
- Can you create internal states for `columnDefs`, `rowData`?
- Can you move `gridApi` into `componentWillLoad` to prevent risk of infinite re-renders?
- Should we not include the **advanced table** in the example apps?
- In React, when I remove `rows`, I get an error: **Unexpected value for cols and rows: undefined** ... If I remove 
the cols, I get: **Unexpected value for cols and rows: ..** and **Unexpected value for cols: undefined**

**Comment by tishoyanchev** [comment]
@verena-ifx 
1 - chip is wrong
2 - enable-filtering is not needed. Why not just filter=sidebar/topbar/none?
3 - why not integrate the filter search inside?
4 - the filter-columns should not have 'search' and don't understand what is 'filter-name'? why is there a need to choose 
the type? single/multi-select? why do the options contain so many properties?

**Comment by verena-ifx** [comment]
> inside

- what do you mean with filter search inside?
- the filtering can happen with single- or multiselect, based on the templates. and that makes sense in my opinion as well.

**Comment by tishoyanchev** [comment]
@verena-ifx 
- Can you resolve the merge conflicts?
- Can ```
 componentDidLoad() {
    this.updateVisibleSlots();
  }
``` be invoked in `componentWillLoad()` instead?

**Comment by tishoyanchev** [comment]
- remove console.log
- the state/prop "visibleSlots" changed during "componentDidLoad()"
- move the story page to the main development section

**Pull request merged**
