### PR TITLE
Stepper: enhanced step customization

### LINKED ISSUE #1307: Stepper: enhance step customization
- User should be able to click on the label of the previous completed steps
- User cannot click on incomplete steps
- Clicking on a completed step makes it a current step
- Current step cannot have an error state enabled
- User should be able to make a step complete, incomplete, current or error via a Prop
- Events should be emitted for every state

### PR DESCRIPTION
**Pull request by akashyeole**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description

Complete state of the step can now be set by new `complete` prop on every step.
And every complete step's label can be clicked to navigate to that step.
Enhanced accessibility of the component.

Related Issue
#1307 

<details>
  <summary>📦 Published PR as canary version: <code>23.4.0--canary.1331.8e7a4869076662c8bb756c563db5831fea87a23c.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@23.4.0--canary.1331.8e7a4869076662c8bb756c563db5831fea87a23c.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@23.4.0--canary.1331.8e7a4869076662c8bb756c563db5831fea87a23c.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@akashyeole 
In addition to what we already discussed:
- add the emitted events in storybook + event description. Look at the example of how it's done with other components
- create an internal state for `activeStep` prop. Props should not be mutated.
- active step cannot be error. When you set `error` to `true` on active step, the label becomes red, but indicator remains active. This should not be the case. Error should have no effect on an active step.
- rename event name from `ifxActiveStepChange` to just `ifxChange`.

**Comment by tishoyanchev** [comment]
- the '`activeStep`' and '`previousStep`' properties of the event object are not numbers showing the active step, but instead
the stepper component itself.

- when I increment the active step, the previous one becomes 'error' by default. It should be completed by default. All the
steps prior to the current active one are by default '`completed`'. 

- too many unnecessary comments for every prop/state/statement

- use `ifx-link` for the labels

**Comment by akashyeole** [comment]
@tishoyanchev 
> * the '`activeStep`' and '`previousStep`' properties of the event object are not numbers showing the active step, but instead the stepper component itself.

1) Fixed - now the `activeStep` and `previousStep` properties of the event object are numbers.

> * when I increment the active step, the previous one becomes 'error' by default. It should be completed by default. All the steps prior to the current active one are by default '`completed`'.

2) Whenever the step is changed, if the previous step is incomplete it will become error by default - this is the current logic  because of which the previous step becomes error. So, user has to mark the step complete explicitly using `step.complete = true`.

     Note - **On load** time all the steps before active step will be complete by default.

> * too many unnecessary comments for every prop/state/statement

3) The comments above every prop will assist the developer to understand its use in a code editor itself. Please see the image
image
image

    I will remove them if you want.

> * use `ifx-link` for the labels 
4) Fixed - used ifx-links (`underlined` variant) in default stepper variant.

**Comment by tishoyanchev** [comment]
1 - when showNumber is true, the number appears on every step, even on the currently active one, thus overriding the activeStep state. This should not be the case. The currently active Step state should not be overridden by the number.
2 - variant by default should be '`default`'. If no variant is specified, it should be the '`default`' one. Currently, if no variant is specified, the component does not render.

**Pull request merged**
