### PR TITLE
Enhancement: footer links now customizable and removable + bump copyright date to current date

### LINKED ISSUE #963: Footer: links should be removable
terms of use, imprint, privacy policy and glossary links should be removable.

### PR DESCRIPTION
**Pull request by verena-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Footer links can be customized (edited and/or removed)

<details>
  <summary>📦 Published PR as canary version: <code>20.46.0--canary.976.41326811ff5057815c9e0df7d3ddfe947c617332.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.46.0--canary.976.41326811ff5057815c9e0df7d3ddfe947c617332.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.46.0--canary.976.41326811ff5057815c9e0df7d3ddfe947c617332.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
1. What is this? **key="medium-https://yourwebsite.com/terms-_blank-true-https://yourwebsite.com/imprint-_blank-true-https://yourwebsite.com/privacy-policy-_blank-true-https://yourwebsite.com/glossary-_blank-true-true-© 1999 - 2022 Infineon Technologies AG"** It's shown on Storybook. 

2. Suggestion: Since the copyright-text is not a link, then I would suggestion instead of having two different Props, one for the text, and one for showing the text, it might be better to just have one, **copyright-text**, and if empty, then simply don't show it. Being empty can be construed as not wanting to have it at all. Same can be applied even for the links. If a link, such as Privacy, does not have link set, then it's essentially not needed, and therefore it might be better to just not show it.

**Comment by verena-ifx** [comment]
> 1. What is this? **key="medium-[https://yourwebsite.com/terms-_blank-true-https://yourwebsite.com/imprint-_blank-true-https://yourwebsite.com/privacy-policy-_blank-true-https://yourwebsite.com/glossary-_blank-true-true-©](https://yourwebsite.com/terms-_blank-true-https://yourwebsite.com/imprint-_blank-true-https://yourwebsite.com/privacy-policy-_blank-true-https://yourwebsite.com/glossary-_blank-true-true-%C2%A9) 1999 - 2022 Infineon Technologies AG"** It's shown on Storybook.
> 2. Suggestion: Since the copyright-text is not a link, then I would suggestion instead of having two different Props, one for the text, and one for showing the text, it might be better to just have one, **copyright-text**, and if empty, then simply don't show it. Being empty can be construed as not wanting to have it at all. Same can be applied even for the links. If a link, such as Privacy, does not have link set, then it's essentially not needed, and therefore it might be better to just not show it.

I am not sure if we can conditionally hide and show props on Storybook. Will investigate. And yes, for the copyright-text, you're absolutely right. I will remove it.

**Comment by verena-ifx** [comment]
> 2\. pyright-text is not a link, then I would suggestion instead of having two different Props, one for the text, and one for showing the text, it might be better to just have one, **copyright-text**, and if empty, then simply don't

fixed point 1 as well

**Comment by verena-ifx** [comment]
> > I am not sure if we can conditionally hide and show props on Storybook. Will investigate. And yes, for the copyright-text, you're absolutely right. I will remove it.
> 
> We can. It's already done for some components. Simply replace the `this.displayGlossaryLink &&` condition, with `this.glossaryUrl &&`, and assign an empty string by default. You could also create a another function to filter the Prop values to make sure it's really empty. In my opinion, if the user does not pass any url value, then they don't want the link to be displayed at all, and therefore we could make the prop value a condition in itself without having to create another Prop for display.

Okay, right! So the same as I have done for the copyright basically. Ill modify the checks and remove the non necessary props

**Pull request merged**
