### PR TITLE
Single Select: Renamed Props for consistency

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Remove the ifx prefix from single-select prop names to match the naming of the multi-select

Related Issue
#1021 

<details>
  <summary>📦 Published PR as canary version: <code>23.0.0--canary.1295.e721759f601079dcf2d6ea4c010da4c8bda9f300.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@23.0.0--canary.1295.e721759f601079dcf2d6ea4c010da4c8bda9f300.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@23.0.0--canary.1295.e721759f601079dcf2d6ea4c010da4c8bda9f300.0
  ```
</details>

### CODE REVIEW

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
Can you also change the props in the example apps?

**Comment by pfafffabian-ifx** [comment]
> @pfafffabian-ifx Can you also change the props in the example apps?

@tishoyanchev done

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
Please make sure to properly examine every instance where the select component is being used, and correct the props. For example, I noticed that the props are not correctly on the Select when it's nested inside the Pagination component.

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev good catch, I fixed it now

**Pull request merged**
