### PR TITLE
Multi Select: Add select all button

### LINKED ISSUE #1131: Multi-select: implement "select-all" feature and make search bar removable
Implement a **select-all** feature for the **multi-select** component.
Pic related:
select all design on dropdown

The feature is to be enabled/disabled via a Prop called `show-select-all` with a default value of `true`.
In additional, make the search-bar also removable via a Prop called `show-search` with a default value of `true`.

Note: 
If the number of selectable-items is less than the total number of options, the `Maximum selectable items` is to be ignored when `select-all` option is clicked.

### PR DESCRIPTION
**Pull request by pfafffabian-ifx**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.

Related Issue
If you opened an issue before creating the PR, point to it here.

Context
image
image
image

<details>
  <summary>📦 Published PR as canary version: <code>24.1.2--canary.1387.796e416217073a07bf70dc560b3c0639f0b3d972.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@24.1.2--canary.1387.796e416217073a07bf70dc560b3c0639f0b3d972.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@24.1.2--canary.1387.796e416217073a07bf70dc560b3c0639f0b3d972.0
  ```
</details>

### CODE REVIEW

**Comment by pfafffabian-ifx** [comment]
I'm a bit confused regarding the pipeline. Github actions adds the last two commits, but they seem to result in a build error for the angular preview.
Did I something wrong?

**Comment by tishoyanchev** [comment]
> I'm a bit confused regarding the pipeline. Github actions adds the last two commits, but they seem to result in a build error for the angular preview. Did I something wrong?

It's not something you did. It could be the new library JQ that Verena installed. Git-actions is showing all the commits from all the PRs in every PR. The Angular fail might be a separate issue. 

Also, can you please resolve the merge conflicts? @pfafffabian-ifx

**Comment by pfafffabian-ifx** [comment]
@tishoyanchev the conflicts are resolved

**Comment by tishoyanchev** [comment]
@pfafffabian-ifx 
1 - rename search-enabled to show-search 
2 - rename  select-all-enabled to show-select-all
3 - remove console log

**Pull request merged**
