### PR TITLE
247 implementation pagination

### PR DESCRIPTION
**Pull request by tishoyanchev**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

The Pagination component. 

**!Do not merge!**

<details>
  <summary>📦 Published PR as canary version: <code>20.21.0--canary.426.063cd0fa02ceacc75d8756ca00ce1e5836f72724.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.21.0--canary.426.063cd0fa02ceacc75d8756ca00ce1e5836f72724.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.21.0--canary.426.063cd0fa02ceacc75d8756ca00ce1e5836f72724.0
  ```
</details>

### CODE REVIEW

**Comment by verena-ifx** [comment]
it would be useful in the example apps to link the pagination to actual elements. So you could create 30 divs with text for example, and then demonstrate a use case with that?

**Comment by tishoyanchev** [comment]
> it would be useful in the example apps to link the pagination to actual elements. So you could create 30 divs with text for example, and then demonstrate a use case with that? not sure if its obvious for the user how to use it like this?

This makes sense, yes, but it requires some efforts, and we have more high-priority tasks. So, I will write it in the backlog, and let's merge this PR now.

**Comment by verena-ifx** [comment]
no events emitted visibly to the user (storybook)

**Comment by verena-ifx** [comment]
@tishoyanchev  can you please check my latest changes in the react example app? the pagination is not working as it should when using some simple mock data

**Comment by verena-ifx** [comment]
please resolve merge conflicts first

**Pull request merged**
