### PR TITLE
added events on dropdown-menu

### PR DESCRIPTION
**Pull request by tishoyanchev**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

I have added events that emit the value of the selected option in the dropdown-menu. 
The event is emitted from dropdown-item, captured in dropdown-menu, and then re-emitted again. 

<details>
  <summary>📦 Published PR as canary version: <code>20.16.3--canary.455.cf6a720b771d8f7b3b2a99ccd9941de15d3a4c6a.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.16.3--canary.455.cf6a720b771d8f7b3b2a99ccd9941de15d3a4c6a.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.16.3--canary.455.cf6a720b771d8f7b3b2a99ccd9941de15d3a4c6a.0
  ```
</details>

### CODE REVIEW

**Comment by verena-ifx** [comment]
Could you change the story name, so the dropdown-menu doesnt appear anymore under "Not reviewed" on Storybook?

**Comment by tishoyanchev** [comment]
> Could you change the story name, so the dropdown-menu doesnt appear anymore under "Not reviewed" on Storybook? Or should I do it? Another thing missing is the action on storybook, so the user can see which events get emitted and what they contain

You can fix those if you have the time so I can focus on the other high-priority issues.

**Comment by verena-ifx** [comment]
Currently, only the dropdown-item emits the event and its not received by the dropdown itself

**Comment by verena-ifx** [comment]
the dropdown event needs to be passed to the parent elements from the dropdown-item. Will add that logic as well

**Pull request merged**
