### PR TITLE
Sidebar: implemented initial-collapse prop

### LINKED ISSUE #949: Sidebar: implement initial-collapse property
Implement an initial-collapse property similar to the Accordion's initial-collapse. When set to true, an item which contains nested items will remain open on load time.

### PR DESCRIPTION
**Pull request by akashyeole**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Description
Implemented initial-collapse prop for ifx-sidebar component

Related Issue
#949 

<details>
  <summary>📦 Published PR as canary version: <code>20.47.0--canary.974.44796bdd8a909cc749622f3e0349a4425aae1889.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @infineon/infineon-design-system-stencil@20.47.0--canary.974.44796bdd8a909cc749622f3e0349a4425aae1889.0
  # or 
  yarn add @infineon/infineon-design-system-stencil@20.47.0--canary.974.44796bdd8a909cc749622f3e0349a4425aae1889.0
  ```
</details>

### CODE REVIEW

**Comment by akashyeole** [comment]
@tishoyanchev fixed -
> * Initial-collapse is not included in Storybook
> * border-indicator is not set correctly. It is set twice.

**Comment by tishoyanchev** [comment]
When multiple items have `active=true`, and **initial-collapse** is set to **true**, only the first active item is not collapsed.

**Comment by akashyeole** [comment]
> When multiple items have `active=true`, and **initial-collapse** is set to **true**, only the first active item is not collapsed.

@tishoyanchev I didn't get you. Did you mean 'initial-collapse is set to **false**'?
The current logic is - if there are multiple items with `active = true`, and `initial-collapse = false`, then only the first active item in the list will be expanded  and rest of them be will untouched

**Comment by tishoyanchev** [comment]
> @tishoyanchev I didn't get you. Did you mean 'initial-collapse is set to ~**true**~ **false**'? The current logic is - if there are multiple items with `active = true`, and `initial-collapse = false`, then only the first active item in the list will be expanded and rest of them be will untouched
> 
> Do you want it to expand all the active items?

Yes, sorry. I meant to say when **initial-collapse** is **false**. 
Yes, the purpose of **initial-collapse** **false** is so active items are not collapsed. There is no logic in applying this to only 1 active item.

**Comment by tishoyanchev** [comment]
- Clean the index.html
- When I make two sibling items active, only the first one becomes active, and I get a console error message that says _only one active item is allowed_. Can you please remove this console error? There is no requirement that users must have only one active item. Also why if the two items are siblings, then both cannot be active, but if another item from another section is active, then that's okay? This should not be the case. Any number of items should be able to be active.

**Pull request merged**
