### PR TITLE
fix: types path incorrect

### PR DESCRIPTION
**Pull request by curtdept**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Typescript was not correctly resolving types. After investigation, types path is incorrect due to changes with bundle directory structure.

### CODE REVIEW

**Comment by verena-ifx** [comment]
@curtdept Thanks! I will test this, as what solved it for us now, was using vite as a build-tool inside the React app instead of React-scripts.

**Comment by tishoyanchev** [comment]
Opened a new issue: https://github.com/Infineon/infineon-design-system-stencil/issues/1472

**Comment by verena-ifx** [comment]
@curtdept unfortunately, changing the types path still does not make the react wrappers work when used inside a react app that was created using react-scripts.

**Comment by curtdept** [comment]
@verena-ifx it was working well for me, however, these newest builds are missing the types completely now :|

image

**Pull request closed without merging**
